name: test.yml
on:
  workflow_dispatch:
env:
  TEST_ENV_VAR: "test env value"

jobs:
    test:
      environment: DEV
      runs-on: ubuntu-latest
      name: test
      steps:
        - run: echo "test=${{ vars.TEST_VAR }}"
    test2:
      environment: DEV
      runs-on: ubuntu-latest
      name: "test"
      steps:
        - run: echo "test ${{ env.TEST_ENV_VAR }}"